### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by dgolez** [TRIQS/h5#11]
### Description

I have some issues with installing. During the compiling, I got an error that a static assertion is violated, see below.
I'm compiling on linux using  GCCcore/11.2.0 CMake/3.22.1-GCCcore-11.2.0 HDF5/1.13 Python/3.9.6-GCCcore-11.2.0

=====

error: static assertion failed: Internal error
   37 |     static_assert(std::is_same<::hsize_t, hsize_t>::value, "Internal error");
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
make[2]: *** [deps/h5/c++/h5/CMakeFiles/h5_c.dir/object.cpp.o] Error 1
make[1]: *** [deps/h5/c++/h5/CMakeFiles/h5_c.dir/all] Error 2
make: *** [all] Error 2
Consolidate compiler generated dependencies of target gtest
[  1%] Built target gtest
Consolidate compiler generated dependencies of target gtest_main
[  3%] Built target gtest_main
Consolidate compiler generated dependencies of target itertools
[  4%] Built target itertools
Consolidate compiler generated dependencies of target h5_c
[  5%] Building CXX object deps/h5/c++/h5/CMakeFiles/h5_c.dir/object.cpp.o
/home/golez/Projects/code/nda/cbuild/deps/h5_src/c++/h5/object.cpp:37:53: error: static assertion failed: Internal error
   37 |     static_assert(std::is_same<::hsize_t, hsize_t>::value, "Internal error");
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
make[2]: *** [deps/h5/c++/h5/CMakeFiles/h5_c.dir/object.cpp.o] Error 1
make[1]: *** [deps/h5/c++/h5/CMakeFiles/h5_c.dir/all] Error 2

 I’ve attached the error returned at the build stage - the issue is that it looks like some assertions
failed, namely  "static assertion failed: Internal error".

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

or paste a minimal code example to reproduce the issue.

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

### Versions

Please provide the application version that you used.

You can get this information from copy and pasting the output of
```bash
python -c "from h5.version import *; show_version(); show_git_hash();"
```
from the command line. Also, please include the OS you are running and its version.

**Comment by Wentzell** [comment]
Fixed in 6c8661a
